name: ui-lib
type: php
docroot: .
php_version: "8.3"
webserver_type: generic
xdebug_enabled: false
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
omit_containers: [db]
nodejs_version: "22"

web_environment: []

router_http_port: "80"
router_https_port: "443"

webimage_extra_packages: []
disable_settings_management: true


additional_hostnames: []

web_extra_exposed_ports:
  - name: storybook
    container_port: 6006
    http_port: 80
    https_port: 443
  - name: vite-server
    container_port: 5173
    http_port: 5173
    https_port: 5174

hooks:
  post-start:
    - exec: pnpm install
